#!/bin/bash -ex

# TODO Get CI going on PRs for both go < 1.18 and >= 1.18

cd $(dirname "$0")
cd $(git rev-parse --show-toplevel)

go test -v ./...
if [ "$(uname -s)" != "Darwin" ]
then
    GOARCH=386 go test -v ./...
fi

go vet ./...
# This exits with 1 even when it successfully installs staticcheck
go install honnef.co/go/tools/cmd/staticcheck || true
staticcheck ./...
# If you run go fmt before 1.18, it is broken
if [ -z "$NO_FORMAT" ]
then
    go fmt ./...
fi

# Check that git is clean
git update-index --refresh
git diff-index --quiet --exit-code HEAD
